### ISSUE TITLE
转换模型，报错：got weight of shape [1024] and normalized_shape = [2048]

### ISSUE THREAD

**Issue by ewwerpm** [MollySophia/rwkv-ncnn#5]
python convert_model.py D:\myProgram\ideaJava\yiZhiXiangMuZu\RWKV\BlinkDL_ChatRWKV\ChatRWKV\fp32-RWKV-4-World-CHNtuned-0.
4B-v1-20230618-ctx4096.pth .\out\
loading... D:\myProgram\ideaJava\RWKV\BlinkDL_ChatRWKV\ChatRWKV\fp32-RWKV-4-World-CHNtuned-0.4B-v1-20230618-ctx4096
Traceback (most recent call last):
  File "D:\python_version\python310\lib\site-packages\torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\myProgram\ideaJava\yiZhiXiangMuZu\RWKV\rwkv-ncnn-master\rwkv\rwkv_v4neo.py", line 164, in forward
    x = self.encoder(token_embd, self.w.blocks[0].ln0.weight, self.w.blocks[0].ln0.bias, self.args.n_embd)
  File "D:\python_version\python310\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\python_version\python310\lib\site-packages\torch\nn\modules\module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\myProgram\ideaJava\yiZhiXiangMuZu\RWKV\rwkv-ncnn-master\rwkv\rwkv_v4neo.py", line 94, in forward
    return F.layer_norm(token_embd, (n_embd,), weight=ln_weight, bias=ln_bias)
  File "D:\python_version\python310\lib\site-packages\torch\nn\functional.py", line 2515, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected weight to be of same shape as normalized_shape, but got weight of shape [1024] and normalized_shape = [2048]
大佬，能指导一下吗？谢谢

**Comment by ewwerpm** [comment]
我把convert_model.py 里的   args.n_embd = 1024 ，原来是2048，改成1024，这一步算是过了
